import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Search, ShoppingCart, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";

interface CartItem {
  produto_id: string;
  produto_codigo: string;
  produto_descricao: string;
  vasilhame_id: string;
  vasilhame_nome: string;
  vasilhame_peso: number;
  quantidade: number;
  preco_por_vasilhame: number;
  peso_total_kg: number;
  preco_por_kg: number;
  margem: number;
  preco_venda_sugerido: number;
  subtotal: number;
}

export function CompraRapida() {
  const [searchTerm, setSearchTerm] = useState("");
  const [cart, setCart] = useState<CartItem[]>([]);
  const [fornecedorId, setFornecedorId] = useState("");
  const [formaPagamento, setFormaPagamento] = useState("");
  const [selectedProduct, setSelectedProduct] = useState<any>(null);
  const [selectedVasilhame, setSelectedVasilhame] = useState("");
  const [quantidade, setQuantidade] = useState(1);
  const [precoVasilhame, setPrecoVasilhame] = useState(0);

  const { data: produtos } = useQuery({
    queryKey: ["produtos", searchTerm],
    queryFn: async () => {
      let query = supabase
        .from("produtos")
        .select(`
          id,
          codigo,
          descricao,
          unidade_venda,
          margem_padrao,
          grupo_id,
          subgrupo_id
        `)
        .eq("ativo", true)
        .limit(50);

      if (searchTerm) {
        query = query.or(`codigo.ilike.%${searchTerm}%,descricao.ilike.%${searchTerm}%`);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data;
    },
  });

  const { data: vasilhames } = useQuery({
    queryKey: ["vasilhames"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("vasilhames")
        .select("*")
        .eq("ativo", true);
      if (error) throw error;
      return data;
    },
  });

  const { data: fornecedores } = useQuery({
    queryKey: ["fornecedores"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("fornecedores")
        .select("*")
        .eq("ativo", true);
      if (error) throw error;
      return data;
    },
  });

  const handleAddToCart = () => {
    if (!selectedProduct || !selectedVasilhame || quantidade <= 0 || precoVasilhame <= 0) {
      toast.error("Preencha todos os campos");
      return;
    }

    const vasilhame = vasilhames?.find(v => v.id === selectedVasilhame);
    if (!vasilhame) return;

    const peso_total_kg = quantidade * vasilhame.peso_kg;
    const preco_por_kg = precoVasilhame / vasilhame.peso_kg;
    const margem = selectedProduct.margem_padrao || 0;
    const preco_venda_sugerido = preco_por_kg * (1 + margem / 100);
    const subtotal = quantidade * precoVasilhame;

    const item: CartItem = {
      produto_id: selectedProduct.id,
      produto_codigo: selectedProduct.codigo,
      produto_descricao: selectedProduct.descricao,
      vasilhame_id: vasilhame.id,
      vasilhame_nome: vasilhame.nome,
      vasilhame_peso: vasilhame.peso_kg,
      quantidade,
      preco_por_vasilhame: precoVasilhame,
      peso_total_kg,
      preco_por_kg,
      margem,
      preco_venda_sugerido,
      subtotal,
    };

    setCart([...cart, item]);
    setSelectedProduct(null);
    setSelectedVasilhame("");
    setQuantidade(1);
    setPrecoVasilhame(0);
    toast.success("Item adicionado ao carrinho");
  };

  const handleRemoveFromCart = (index: number) => {
    setCart(cart.filter((_, i) => i !== index));
    toast.success("Item removido do carrinho");
  };

  const handleFinalizarCompra = async () => {
    if (cart.length === 0) {
      toast.error("Carrinho vazio");
      return;
    }

    if (!fornecedorId || !formaPagamento) {
      toast.error("Selecione fornecedor e forma de pagamento");
      return;
    }

    try {
      // Create purchase
      const { data: compra, error: compraError } = await supabase
        .from("compras")
        .insert([{
          fornecedor_id: fornecedorId,
          forma_pagamento: formaPagamento,
          status: "rascunho",
          valor_produtos: cart.reduce((sum, item) => sum + item.subtotal, 0),
          valor_total: cart.reduce((sum, item) => sum + item.subtotal, 0),
          numero_compra: 0, // Will be auto-generated by trigger
        }])
        .select()
        .single();

      if (compraError) throw compraError;

      // Insert items
      const items = cart.map(item => ({
        compra_id: compra.id,
        produto_id: item.produto_id,
        vasilhame_id: item.vasilhame_id,
        quantidade_vasilhames: item.quantidade,
        peso_total_kg: item.peso_total_kg,
        preco_por_vasilhame: item.preco_por_vasilhame,
        preco_por_kg: item.preco_por_kg,
        subtotal: item.subtotal,
        margem_aplicada: item.margem,
        preco_venda_sugerido: item.preco_venda_sugerido,
      }));

      const { error: itensError } = await supabase
        .from("itens_compra")
        .insert(items);

      if (itensError) throw itensError;

      // Update products
      for (const item of cart) {
        await supabase
          .from("produtos")
          .update({
            preco_ultima_compra: item.preco_por_kg,
            data_ultima_compra: new Date().toISOString(),
            vasilhame_ultima_compra_id: item.vasilhame_id,
          })
          .eq("id", item.produto_id);
      }

      toast.success(`Compra #${compra.numero_compra} registrada com sucesso!`);
      setCart([]);
      setFornecedorId("");
      setFormaPagamento("");
    } catch (error: any) {
      toast.error(`Erro ao finalizar compra: ${error.message}`);
    }
  };

  const totalCompra = cart.reduce((sum, item) => sum + item.subtotal, 0);

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      {/* Left: Product Selection */}
      <div className="lg:col-span-2 space-y-6">
        <Card>
          <CardHeader>
            <CardTitle>Buscar Produtos</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="relative">
              <Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Buscar por código ou descrição..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-9"
              />
            </div>

            <div className="max-h-96 overflow-y-auto space-y-2">
              {produtos?.map((produto) => (
                <div
                  key={produto.id}
                  onClick={() => setSelectedProduct(produto)}
                  className={`p-3 rounded-lg border cursor-pointer transition-colors ${
                    selectedProduct?.id === produto.id
                      ? "border-primary bg-primary/5"
                      : "border-border hover:border-primary/50"
                  }`}
                >
                  <div className="flex justify-between items-start">
                    <div>
                      <div className="font-medium">{produto.codigo}</div>
                      <div className="text-sm text-muted-foreground">{produto.descricao}</div>
                    </div>
                    <div className="text-sm text-muted-foreground">
                      {produto.unidade_venda}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {selectedProduct && (
          <Card>
            <CardHeader>
              <CardTitle>Adicionar ao Carrinho</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="text-sm font-medium">Vasilhame</label>
                  <Select value={selectedVasilhame} onValueChange={setSelectedVasilhame}>
                    <SelectTrigger>
                      <SelectValue placeholder="Selecione" />
                    </SelectTrigger>
                    <SelectContent>
                      {vasilhames?.map((v) => (
                        <SelectItem key={v.id} value={v.id}>
                          {v.nome} ({v.peso_kg}kg)
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <label className="text-sm font-medium">Quantidade</label>
                  <Input
                    type="number"
                    min={1}
                    value={quantidade}
                    onChange={(e) => setQuantidade(Number(e.target.value))}
                  />
                </div>

                <div className="col-span-2">
                  <label className="text-sm font-medium">Preço por Vasilhame (R$)</label>
                  <Input
                    type="number"
                    step="0.01"
                    min={0}
                    value={precoVasilhame}
                    onChange={(e) => setPrecoVasilhame(Number(e.target.value))}
                  />
                </div>
              </div>

              {selectedVasilhame && quantidade > 0 && precoVasilhame > 0 && (
                <div className="p-4 rounded-lg bg-muted space-y-2 text-sm">
                  <div className="flex justify-between">
                    <span>Peso Total:</span>
                    <span className="font-medium">
                      {(quantidade * (vasilhames?.find(v => v.id === selectedVasilhame)?.peso_kg || 0)).toFixed(2)} kg
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span>Preço/kg:</span>
                    <span className="font-medium">
                      R$ {(precoVasilhame / (vasilhames?.find(v => v.id === selectedVasilhame)?.peso_kg || 1)).toFixed(2)}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span>Preço Venda Sugerido/kg:</span>
                    <span className="font-medium text-primary">
                      R$ {((precoVasilhame / (vasilhames?.find(v => v.id === selectedVasilhame)?.peso_kg || 1)) * (1 + (selectedProduct.margem_padrao || 0) / 100)).toFixed(2)}
                    </span>
                  </div>
                  <div className="flex justify-between pt-2 border-t">
                    <span className="font-semibold">Subtotal:</span>
                    <span className="font-semibold text-lg">
                      R$ {(quantidade * precoVasilhame).toFixed(2)}
                    </span>
                  </div>
                </div>
              )}

              <Button onClick={handleAddToCart} className="w-full">
                <Plus className="h-4 w-4 mr-2" />
                Adicionar ao Carrinho
              </Button>
            </CardContent>
          </Card>
        )}
      </div>

      {/* Right: Cart */}
      <div className="space-y-6">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <ShoppingCart className="h-5 w-5" />
              Carrinho ({cart.length})
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {cart.length === 0 ? (
              <p className="text-sm text-muted-foreground text-center py-8">
                Carrinho vazio
              </p>
            ) : (
              <div className="space-y-2 max-h-96 overflow-y-auto">
                {cart.map((item, index) => (
                  <div key={index} className="p-3 rounded-lg bg-muted space-y-1">
                    <div className="flex justify-between items-start">
                      <div className="flex-1">
                        <div className="font-medium text-sm">{item.produto_codigo}</div>
                        <div className="text-xs text-muted-foreground">{item.produto_descricao}</div>
                      </div>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleRemoveFromCart(index)}
                      >
                        <Trash2 className="h-4 w-4 text-destructive" />
                      </Button>
                    </div>
                    <div className="text-xs space-y-0.5">
                      <div>{item.quantidade}x {item.vasilhame_nome} = {item.peso_total_kg.toFixed(2)}kg</div>
                      <div>R$ {item.preco_por_kg.toFixed(2)}/kg</div>
                      <div className="font-semibold text-primary">R$ {item.subtotal.toFixed(2)}</div>
                    </div>
                  </div>
                ))}
              </div>
            )}

            {cart.length > 0 && (
              <>
                <div className="pt-4 border-t space-y-3">
                  <div>
                    <label className="text-sm font-medium">Fornecedor</label>
                    <Select value={fornecedorId} onValueChange={setFornecedorId}>
                      <SelectTrigger>
                        <SelectValue placeholder="Selecione" />
                      </SelectTrigger>
                      <SelectContent>
                        {fornecedores?.map((f) => (
                          <SelectItem key={f.id} value={f.id}>
                            {f.nome_fantasia || f.razao_social}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>

                  <div>
                    <label className="text-sm font-medium">Forma de Pagamento</label>
                    <Select value={formaPagamento} onValueChange={setFormaPagamento}>
                      <SelectTrigger>
                        <SelectValue placeholder="Selecione" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="BOLETO">Boleto</SelectItem>
                        <SelectItem value="NOTA FISCAL">Nota Fiscal</SelectItem>
                        <SelectItem value="PIX">PIX</SelectItem>
                        <SelectItem value="DINHEIRO">Dinheiro</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <div className="flex justify-between text-lg font-bold pt-2">
                    <span>Total:</span>
                    <span>R$ {totalCompra.toFixed(2)}</span>
                  </div>
                </div>

                <Button onClick={handleFinalizarCompra} className="w-full" size="lg">
                  Finalizar Compra
                </Button>
              </>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
